### ISSUE TITLE
xcode 7

### ISSUE THREAD

**Issue by akaralar** [jonreid/XcodeWarnings#1]
any plans to update this for xcode 7? i don't know as much as you as to how you look up available values of warnings, i'm interested in helping out if you show the way :)

**Comment by jonreid** [comment]
Surprisingly, Xcode 7 didn't seem to add any new warnings! It did remove one, which I will fix.

**Comment by jonreid** [comment]
New in ece7e61: CLANG_WARN_NULLABLE_TO_NONNULL_CONVERSION
