### ISSUE TITLE
Open source extraction script?

### ISSUE THREAD

**Issue by guillaumealgis** [jonreid/XcodeWarnings#3]
Thanks a lot for this project, this is super useful :+1: 

I was wondering how you extracted the variables names from Xcode, and if you would consider open-sourcing the script (if you're using one)?

**Comment by jonreid** [comment]
I do it by hand ;-|

**Comment by guillaumealgis** [comment]
FYI, I wrote a little python script to extract the warnings from Xcode and format them in the xcconfig format:
https://github.com/guillaume-algis/XcodeWarningsAsXcconfig

**Comment by jonreid** [comment]
Cool! Thanks for letting me know
