### ISSUE TITLE
Please include Pedantic Warnings, even if commented out

### ISSUE THREAD

**Issue by FlashSheridan** [jonreid/XcodeWarnings#5]
First, thanks very much, this is very cool.  But I would suggest including `GCC_WARN_PEDANTIC`, even if commented out, so that people not including unpedantic libraries can try it.  (It might also encourage maintainers to fix the problems.)  Not urgent for me; including your file plus an override file seems simple enough.

**Comment by FlashSheridan** [comment]
https://github.com/jonreid/XcodeWarnings/pull/6

**Comment by jonreid** [comment]
Merged
