### ISSUE TITLE
Why is GCC_WARN_UNUSED_PARAMETER commented out?

### ISSUE THREAD

**Issue by acecilia** [jonreid/XcodeWarnings#7]
`GCC_WARN_UNUSED_PARAMETER` is the only build setting that is commented out without a rationale. I was wondering why.

Thanks!

**Comment by jonreid** [comment]
From the README:

"Unused Parameters" (GCC_WARN_UNUSED_PARAMETER) isn't enabled because it's not unusual to provide a method required by Apple's frameworks that ignores a parameter.

Of course, you can change this locally. I find it quite noisy.
