### ISSUE TITLE
Some missing warnings

### ISSUE THREAD

**Issue by snej** [jonreid/XcodeWarnings#8]
Here are some warnings that are missing from the config file. I don't know the Xcode build setting names for any of these, just the Clang flags:

```
-Woverriding-method-mismatch    // Obj-C method override has different return type from super
-Weffc++                        // Warnings from the classic "Effective C++" book
-Wcall-to-pure-virtual-from-ctor-dtor   // Calling a pure virtual method from a ctor/dtor
-Wmemset-transposed-args        // Mixing up size and value args of memset()
-Wreturn-std-move               // Tricky case where returning triggers a copy w/o std::move()
-Wsizeof-pointer-div            // "sizeof(a) / sizeof(a[0])" where a is a pointer not an array
-Wdefaulted-function-deleted    // Can't default-construct this class
```
The first two have been around for years. The rest are apparently new in the version of Clang in Xcode 11. They were described in "What's New In Clang And LLVM" (WWDC '19).

In the absence of build-setting names, I've just been setting these by adding this line:
```
WARNING_CFLAGS = -Woverriding-method-mismatch -Weffc++ -Wcall-to-pure-virtual-from-ctor-dtor -Wmemset-transposed-args -Wreturn-std-move -Wsizeof-pointer-div -Wdefaulted-function-deleted
```

**Comment by jonreid** [comment]
Thank you for these.

I believe -Woverriding-method-mismatch is already included, only with the Xcode name GCC_WARN_ABOUT_RETURN_TYPE.

And -Weffc++ seems to be a synonym for -Wnon-virtual-dtor. Its Xcode name is GCC_WARN_NON_VIRTUAL_DESTRUCTOR.

So I think we're good on the first two. I'll look for the rest in Xcode 11 in case they have build setting names. Otherwise, I'll probably use your trick.

Thanks for the heads-up

**Comment by snej** [comment]
`-Weffc++` does more than warn about nonvirtual destructors, or at least it used to. It checks several best practices from _Effective C++_, including putting member initializers in the same order as their declarations. (But come to think of it, I don't think I've seen any nags about that in a while. Maybe it doesn't anymore.)

**Comment by jonreid** [comment]
I wonder if they ditched some of those? https://clang.llvm.org/docs/DiagnosticsReference.html#weffc only points to the destructor thing.

**Comment by jonreid** [comment]
And hmm, reading the transcript of the session you reference: "I'm going to tell you about five diagnostics that are all on by default in Xcode 11." They're on, so adding flags to turn them on is unnecessary.
